### ISSUE TITLE
Issue with Peacekeeper rechamber

### ISSUE THREAD

**Issue by Black-DeathZM** [dtzxporter/cast#5]
Hi,

I've encountered another cast animation issue, you may already be aware of it, but just in case not thought I'd report.

With the Peacekeeper rechamber (rechamber_0 of ptpov_peacekeeper), the right arm does not correctly follow the lever and instead offsets way off, which it does not do in-game.

Here's how the animation looks in Maya: https://gyazo.com/2c85166176edd213aca44fb6ba53ebd8

**Comment by dtzxporter** [comment]
Does the seanim do the same thing?

**Comment by Black-DeathZM** [comment]
Nope - here it is on SEAnim: https://twitter.com/scobalula/status/1214889316750647296

As can be seen with the SEAnim the hand stays with the weapon, whereas on cast the arm goes off away

**Comment by dtzxporter** [comment]
Ok so we investigated this and scobs tool doesn't add keyframes if they didn't previously exist (Reason why the right arm looks semi-ok, but when played on a weapon, it still fails). I tracked this down some more and this is a bug in how Legion handles apex additive export which needs to be updated to provide a supported file.

Closing because this isn't related to cast, but related to the exporter.
